version: '3.8'
services:
  web-api:
    image: img
    container_name: prodia-api
    ports:
      - '8080:80'
    env_file:
      - .env
  web-portal:
    image: img
    container_name: prodia-ui
    ports:
      - '3000:3000'
    env_file:
      - .env