name: PROD - Build

on:
  push:
    branches: [ main ]

env:
  run_id: PROD-portal-${{ github.run_id }}

jobs:
  
  build:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd simple-demo-app
          docker build -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{ env.run_id }} .
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{ env.run_id }}
          echo ::set-output name=image::$ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Install yq cli tool
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install yq
          yq --version

      - name: Download docker-compose.yml file
        run: |
          aws s3 cp s3://${{ vars.S3_BUCKET }}/docker-compose.yml .
          cat docker-compose.yml

      - name: Update docker-compose.yml file with docker image url
        run: |
          yq e -i '.services.client-app.image="${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ env.run_id }}"' docker-compose.yml
          cat docker-compose.yml
      
      - name: Push updated docker-compose.yml file with corresponding zip file
        run: |
          # zip Dockerrun.zip docker-compose.yml
          aws s3 cp docker-compose.yml s3://${{ vars.S3_BUCKET }}
          # aws s3 cp Dockerrun.zip s3://${{ vars.S3_BUCKET }}
