name: TEST - Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  deploy-to-elastic-beanstalk:
    name: Deploy to elastic beanstalk
    runs-on: ubuntu-latest
    environment: Test
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download ${{ vars.LAST_RUN_ID }} file
        run: aws s3 cp s3://${{ vars.S3_BUCKET }}/${{ vars.S3_BUCKET_DIR }}/${{ vars.LAST_RUN_ID }} .

      - name: Deploy to Elastic Beanstalk
        run: |
          RUN_ID=`cat ${{ vars.LAST_RUN_ID }}`
          aws elasticbeanstalk update-environment --application-name ${{ vars.EB_APPLICATION }} --environment-name ${{ vars.EB_ENVIRONMENT }} --version-label $RUN_ID