name: Validation pipeline

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js project
        uses: actions/setup-node@v2
        with:
          node-version: 18.x.x

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test